### ISSUE TITLE
Issues using local weather server

### ISSUE THREAD

**Issue by rmloeb** [OpenSprinkler/OpenSprinkler-Weather#35]
I'm trying to make weather-server work so I can then make Zimmerman work.  I have weather-server running on Ubuntu 18.04 and I'm using OWM.  Location is set to a specific place on the map, which starts out as "Colorado, USA" and then changes, presumably after a call to OWM, to "The Pinery, US,"  It's been decades since I got this deep into code and all the APIs are new :-(

Issue: Last successful weather call is empty.  Last weather call a few minutes ago, and current temp and forecast have updated.  I know there have been problems with Diagnostics.  Is this a reflection of that issue and not of what's going on with weather-server?

Issue: Current temp is displayed in Centigrade, but was in Fahrenheit.  Ooops.  Changed back to Fahrenheit after last weather call.

Issue: OS says water level is 56%.  Direct call to weather-server says 0%.  Zimmerman parameters are the same.
Call: http://192.168.0.91:3000/weather1.py?loc=39,-104&wto=%22\%22h\%22:100,\%22t\%22:100,\%22r\%22:100,\%22bh\%22:40,\%22bt\%22:70,\%22br\%22:0%22
Response: &scale=0&rd=-1&tz=24&sunrise=342&sunset=1205&eip=3232235668&rawData={"h":57.13,"p":0.01,"t":45.2,"raining":0}

Issue: Forecast is populated, but the forecast disagrees with what OWM is displaying on their site.  (See attached, one of which is a screen capture from OS and the other from OWM, taken immediately after OS updated.)
[OS Forecast-The Pinery-2008 hours-05182019.pdf](https://github.com/OpenSprinkler/OpenSprinkler-Weather/files/3194571/OS.Forecast-The.Pinery-2008.hours-05182019.pdf)
[OWM Forecast-The Pinery-2010hours-05182019.pdf](https://github.com/OpenSprinkler/OpenSprinkler-Weather/files/3194572/OWM.Forecast-The.Pinery-2010hours-05182019.pdf)

Clarification needed: Does weather-server do the accumulation and averaging required to make Zimmerman work?  I seem to recall reading that it did, but my feeble brain may be fooling me.

Once I get past this, I will set up weewx to capture the output from my Davis weather station and feed it to weather-server.

Thank you for any/all guidance!!!

Rog

**Comment by PeteBa** [comment]
@rmloeb , thanks for detailing all of this out as it makes it much easier to both replicate and diagnose. Hoping the following points help clarify.

1) Last Successful Call Showing Empty: This indicates an error when calling the Weather Service. Is this still the case after leaving the system running for a few hours as OS only generates a Weather call every two hours. ? [Note: you can "force" a new weather call by going into the Map and changing your location slightly then saving (submit) the new location]

2) Data On The Diagnostic Page: The values shown for temp, humidity, precip are not correctly displayed on this page. The values from Water Level, Last Weather Call and Last Successful Call should all still be valid. To fix this requires co-ordinated changes across Weather Service, Firmware and App that will take some time to arrange and test. The best way of diagnosing any issues at the moment is by generating a browser call to the Weather Service and examining the results.

3) Display Showing Centigrade: The App shows temp/rainfall in local units (basically metric everywhere except for US and a couple others). It determines locale from the location selected in the Map via the Settings page in App. If you have changed your Map location then this might cause the display to swap from metric to imperial. Is it still showing the correct units ?

4) OS Showing Different to Weather Call: This is a good catch and highlights an error in the instructions that I will clarify. Can you try again using the the following format for the browser call and confirm that it returns a similar result to OS (Note that timing differences may result in small differences):
```
http://192.168.0.91:3000/weather1.py?loc=39,-104&wto="h":100,"t":100,"r":100,"bh":40,"bt":70,"br":0
```
5) OWM Site Differs From OS: OWM shows the average daytime (orange box) and average nightime (grey box) temperature rather than the min and max as shown by App. 

6) Zimmerman Cal: Yes, an OWM forecast provides 8 temperature values for each of the next three hour periods. The Weather Service calculates the mean value of these results to represent the average temperature across the next 24 hours. Similarly for Humidity and Precipitation. This provides the set of inputs to the zimmerman calculation.

Let me know how you get on.

**Comment by rmloeb** [comment]
1.  Last Successful Call still empty.  Been running for 18 hours.  (My OS seems to generate a weather call every hour.)  Is there a log function or something else I could use to debug the apparently erroneous weather-service call?  I'm getting some data back, e.g., current temp and a forecast but not the correct water level, so the call isn't completely failing.  [I'm reluctant to fiddle with your code; my C++ was once quite good...thirty years ago!]

3.  Display seems to have stabilized on Fahrenheit.

4.  OS showing water level of 56%.  Manual call to weather-server, using the corrected URL you provided, says scale=23.  (Note: the call I used was copied directly from the documentation with values substituted for location, so there may be an error in the original example.)

6.  Your explanation of the Z calculation using forecast data requires further study.  I believe that Z intended to use actual (prior day) data.  This is important when determining water level, i.e., it doesn't make much sense to water if it rained buckets the day before.  I have to think through the implications of using forecast data, which may make more sense in some situations.  In my case, watering takes place shortly after midnight with the intention of "making up for the rain that didn't fall the previous day."  (Colorado is high desert, and we get huge weather swings, often within a few hours, so the "make up" strategy tends to be effective.  We also get rainfall that varies substantially within a small area, which is why I've got to get back to using my PWS data.)

I appreciate your engagement and responsiveness!

**Comment by PeteBa** [comment]
The fact that OS is updating every hour suggests that you are on an older version of the firmware. It might be worth updating if only to rule that out. I'm not aware of an issue with the older firmware but you never know. 

Just so you know there are two types of weather calls that OS makes. The first is to request 7-8 day outlook that is used for the information on the main screen and when you click the weather icon. This **does not** use the local Weather Service and it sounds like this is working for you so this would confirm internet connectivity. The second type of call is specifically to run the zimmerman calculation and this **does** use the local Weather Service. It is this call that is logged in the Diagnostic popup (LWC and LSWC). It looks like this isnt working.

On point 1 and 3, if you aren't seeing both valid `Last Weather Call` and `Last Successful Weather Call` dates then the Water Level (56%) is not a valid comparison with the 23% from Weather Service directly. Something else is amiss.  So for some reason OS is not successfully communicating with the local Weather Service.

Just to cover all of the basics, can you
- Confirm that Zimmerman is selected in the Options Page and that the contents of the Weather field in the `http://<OS IP>/su` page match the IP:PORT of your Ubuntu box
- What do you have in your `.env` file on the Ubuntu box. The HOST variable should be "0.0.0.0", PORT should match what you used in the `/su` page, OWM_API_KEY should be set to a valid key and the PWS field should NOT be present if using OWM.
- If you reboot the OS then what does the Water Level default to ?
- If you run `sudo systemctl -u weather.service` at the Ubuntu prompt  then you should see a few logging messages that confirm the service is running

Sorry for all of the questions but looking to rule out a few things.

On point 4, WU supported historic data the OWM supports forecasts. The counter-argument is that if a downpour is forecast in the next three hours then why water. But look I'm not seeking to debate the merits, just stating how it is.

**Comment by rmloeb** [comment]
Firmware is V 2.17.  I cannot identify a later version.  2.18 seems to be for OSPi; is there a version for the original OS device (circa 2015)?.  (I vaguely recall going through a very complex update process, perhaps a couple of years ago, requiring a special device and cable or something like that.  Doubtful I can find whatever that was...)

Confirming Z selected in Options and su/Weather field is correct.  
JavaScript:	https://ui.opensprinkler.com/js
Default:	        https://ui.opensprinkler.com/js
Weather:	        192.168.0.91:3000
Default:	         weather.opensprinkler.com
Password:	
 
Confirming .env for weather-service:
HOST=0.0.0.0
PORT=3000
WEATHER-PROVIDER=OWM
OWM_API_KEY=05df1ca4115bf0ed023f1bc35101dac5
(When I get everything running, I'll get a new OWM key.)

Rebooted OS; Water Level defaults to 56%, which seems to a constant.  Incidentally, temp units reverted to Centigrade, later switched to F.   In Diagnostics, humidity reports at 66%, mean temp 51, precip 0.4, which is roughly what a manual call is reporting (variance probably due to difference in time).  Last Successful Weather Call still blank.  

journalctl reports no messages for weather.service since it was started yesterday.  Stopped and restarted it and journalctl reports listening on port 3000.

Service appears to operate as expected when called directly:
Call: http://192.168.0.91:3000/weather1.py?loc=39.4,-104.7&wto=%22h%22:100,%22t%22:100,%22r%22:100,%22bh%22:40,%22bt%22:70,%22br%22:0
Return: &scale=0&rd=-1&tz=24&sunrise=343&sunset=1210&eip=3232235668&rawData={"h":60.38,"p":0.04,"t":51.5,"raining":0}
Actual current temp, reported at The Pinery (closest locale) by OWM is 51 but humidity is 34% (although DarkSky reports humidity at 50% and temp at 52; humidity has been widely variable all day).

Just to be sure of everything, I ran npm install again and got these messages:
npm WARN os-weather-service@1.0.2 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
Is there an actual error of some kind?

Understand your position re Z.  Gotta use what's available.  My difficulty is that any forecast is highly unreliable for this area, particularly rain forecast amounts as of midnight.  Sometimes it actually rains; sometimes is doesn't.  Working from actual data was much more accurate.  Once I get weather-service working, I'll go to work on weewx collecting the data from my PWS.

**Comment by PeteBa** [comment]
OK. So the setup looks good but it doesnt look like OS is communicating with Weather Service. So what we can do is add some logging:
- firstly lets stop the weather.service by `$ sudo systemctl stop weather.service`
- then open the file `routes/weather.ts` in an editor to enable/add some basic logging
- scroll down and delete Lines 324 and 326 so that the remaining `console.log()` line is enabled
- at blank line 230 add `console.log( "OpenSprinkler Weather Query: %s", JSON.stringify( req.query ) );`
- you will need to recompile the solution using `$ npm run compile` and start the service via the command line with `$ npm start`
- this should then start logging requests from OS and the responses generated to the console. Note, the information will only be generated each hour so you may need to wait a bit or force a call by changing your location in the App/Options/System/Location page.

If the above doesn't yield any output then I suspect a network/firewall problem.

**Comment by rmloeb** [comment]
Made the changes.  If I make a manual call from a browser, I get the two log records.  If I reboot OS or change the location, I do **not** get console output.  OS is not making the call, but it seems to be getting data from somewhere.  I suspect it is using the default: weather.opensprinkler.com and ignoring what I entered in /su.  

The data being returned from the manual call is curious.  Is that supposed to be actual or forecast?

**Comment by PeteBa** [comment]
The data returned from the manual call is forecast data (i.e. mean Temp and Humidity for the next 24-hours and aggregated Precipitation for next 24-Hours). It is not ignoring what is in `/su` but rather making two different calls, one for the outlook and one for the zimmerman calc. The zimmerman calc goes to the local Weather Service (this is failing) and the weather outlook call goes out to weather.opensprinkler.com (this is succeeding).

OS is not talking to the local Weather Service but I'm afraid that I don't see an obvious next step. The fact that you can connect via a browser suggests firewall rules aren't the issue. The Weather Service is listening so that's good. And OS seems configured to talk to the Ubuntu box at 192.168.0.91. So I don't know where that leaves us. Last thought is to see if the Ubuntu box can "ping" the OS device. That would at least confirm some basic network connectivity.

**Comment by rmloeb** [comment]
Yes, the Ubuntu box can ping the OS device.

I reviewed whether to update to firmware 2.18 and the warning was not to do so unless I needed the extended number of expansion boards. so I didn't.

I am as mystified as you are...  I created a HOSTS record in the local DNS resolver so that I could put a fully-formed URL into /su, but that made no difference.  And I removed the wireless AP that connected the OS to the network and cabled it, temporarily.   No calls are going to the weather-server from OS.

**Comment by rmloeb** [comment]
Ray says "The custom weather URL does NOT support port other than 80."  Attempting to move to another box.

**Comment by rmloeb** [comment]
Temporarily moved weather-service to another box, where port 80 was available.  Call from OS now works!  You may wish to  upgrade your documentation.

**Comment by PeteBa** [comment]
@rmloeb , thanks for helping work through this. Yep, Ray is spot on and port 80 is hardcoded into OS (but not OSPi). I will update the documentation.
